#! /bin/sh

pulseaudio -D
sxhkd &
polybar bar &
compton &
dunst ~/.config/dunst/dunstrc &

#wal -i /home/ajay/Pictures/Trees.jpg &


feh --bg-scale /home/ajay/Pictures/Mountain.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width                0
bspc config window_gap                  12
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config auto_alternate              false
bspc config auto_cancel                 true
#bspc config top_padding                 20
#bspc config bottom_padding 		10
bspc config top_padding 		20
bspc config bottom_padding 		10
#bspc config normal_border_color         \#5500223a
bspc config focused_border_color        #55C878A0 #orangish border color
#bspc config focused_border_color     	\#00ffffff
bspc config presel_border_color         \#AC4142

#bspc config normal_frame_opacity        0.5
#bspc config focused_frame_opacity       0.7
