#! /bin/sh

sxhkd &
compton &
polybar bar &

feh --bg-center /home/ajay/Pictures/snow_mountain.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d I II III IV V


bspc config border_width                3.5
bspc config window_gap                  20
bspc config split_ratio                     0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       false
bspc config auto_alternate              false
bspc config auto_cancel                 true
bspc config top_padding                 16
bspc config bottom_padding 		16
bspc config normal_border_color         "#632F9C"
bspc config focused_border_color        "#C878A0"
bspc config presel_border_color         "#AC4142"

bspc config normal_frame_opacity        0.3
bspc config focused_frame_opacity       0.5

